### ISSUE TITLE
Lab 1 "elevator pitch" and jupyter-online Deliverable

### ISSUE THREAD

**Issue by birdsofjay** [birdsofjay/msbx5500-spring-2020#1]
@deargle These are my 'little elevator-pitch-length responses'. ~I'm working on using them more and will get example screenshots.~
[lab1_response](/birdsofjay/msbx5500-spring-2020/blob/master/Lab1/lab1_deliverable.md)

**Comment by deargle** [comment]
Good job with this so far -- still need to see the other 6 kaggle tutorials

**Comment by deargle** [comment]
Also need to see your answers to the "Job market" section of lab 1

**Comment by deargle** [comment]
I'll open new "issues" for those two separate deliverables

**Comment by deargle** [comment]
Closing because "elevator pitch" and jupyter-online deliverables look good. See other issue-deliverables though
